// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5yzSSSLl1DR2eAH2rGLVPosZ8Xu3aKuA',
    appId: '1:393595933155:web:3ae2f4e4a2a2ad2a9210d6',
    messagingSenderId: '393595933155',
    projectId: 'reciperealm-7b6e5',
    authDomain: 'reciperealm-7b6e5.firebaseapp.com',
    storageBucket: 'reciperealm-7b6e5.appspot.com',
    measurementId: 'G-ECJLJXG8D5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKOs_wcvvTzzSHpQNwiQDcdJO8xn6dHkg',
    appId: '1:393595933155:android:007dd8083d6544749210d6',
    messagingSenderId: '393595933155',
    projectId: 'reciperealm-7b6e5',
    storageBucket: 'reciperealm-7b6e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASVxrIXvM6iXB8Lb5BZomLELiNBQRlbZQ',
    appId: '1:393595933155:ios:e2235838e9503ecd9210d6',
    messagingSenderId: '393595933155',
    projectId: 'reciperealm-7b6e5',
    storageBucket: 'reciperealm-7b6e5.appspot.com',
    iosClientId: '393595933155-iu1msq5t3sbqp6ef1b8c2fu0jv5vcn3a.apps.googleusercontent.com',
    iosBundleId: 'com.example.reciperealm',
  );
}
